In [2]:
import numpy as np

In [28]:
def tokenizer(pt, eta, ):
    pt_bins = [0] + np.arange(20, 30, 2).tolist()
    eta_bins = [0, 0.5, 1.0, 1.5, 2.0, 2.5]
    pt_idx = np.digitize(pt, pt_bins) - 1
    eta_idx = np.digitize(eta, eta_bins) - 1
    flatten_idx = pt_idx * len(eta_bins) + eta_idx
    return flatten_idx

In [34]:
pt_bins = [0] + np.arange(20, 32, 2).tolist() + np.arange(33, 50, 3).tolist() + np.arange(52, 100, 4).tolist() + np.arange(100, 200, 5).tolist() + np.arange(200, 1000, 10).tolist() + np.arange(1000, 2000, 20).tolist()
print(len(pt_bins))
eta_bins = np.arange(0, 2.5, 0.01).tolist()
print(len(eta_bins))
print("total bins: ", len(pt_bins) * len(eta_bins))

175
250
total bins:  43750


In [25]:
mesh = np.mgrid[:len(pt_bins), :len(eta_bins)]
mesh.shape

(2, 11, 6)

In [18]:
mesh[0, :, 0], mesh[0], mesh[0, 2, :], mesh[1, 2, :], mesh[1, 2, :]

(array([0, 1, 2]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]),
 array([2, 2, 2]),
 array([0, 1, 2]),
 array([0, 1, 2]))