In [1]:
import numpy as np

Assuming there are five measurements, the error of each measurement is saved at *error*. 
It's easy to calculate the sum of the five measurements, but how about the error?

In [21]:
error = np.linspace(1, 5, 5)
print(a)

[ 1.  2.  3.  4.  5.]


In [22]:
uncorrelated = np.diag(a*a)
print(uncorrelated)

[[  1.   0.   0.   0.   0.]
 [  0.   4.   0.   0.   0.]
 [  0.   0.   9.   0.   0.]
 [  0.   0.   0.  16.   0.]
 [  0.   0.   0.   0.  25.]]


In [23]:
correlated = np.outer(a, a)
print(correlated)

[[  1.   2.   3.   4.   5.]
 [  2.   4.   6.   8.  10.]
 [  3.   6.   9.  12.  15.]
 [  4.   8.  12.  16.  20.]
 [  5.  10.  15.  20.  25.]]


In [40]:
jacobian = np.ones(5)
print(jacobian)

[ 1.  1.  1.  1.  1.]


In [42]:
np.sqrt(np.matmul(jacobian, np.matmul(uncorrelated, jacobian.transpose())))

7.416198487095663

In [43]:
np.sqrt(np.matmul(jacobian, np.matmul(correlated, jacobian.transpose())))

15.0

In [45]:
np.sqrt(sum([x**2 for x in error]))

7.416198487095663

In [46]:
sum(error)

15.0

In [4]:
def to_one_hot(indices, max_value, axis=-1):
  one_hot = np.eye(max_value)[indices]
  if axis not in (-1, one_hot.ndim):
    one_hot = np.moveaxis(one_hot, -1, axis)
  return one_hot

In [7]:
one_hot = np.eye(4)[2]
print(one_hot)
axis = 1
if axis not in (-1, one_hot.ndim):
    one_hot = np.moveaxis(one_hot, -1, axis)
print(one_hot)

[ 0.  0.  1.  0.]
[ 0.  0.  1.  0.]


In [8]:
from scipy import spatial

In [14]:
i_, j_ = np.meshgrid(range(3), range(3), indexing='ij')

In [16]:
i_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [17]:
i_.ravel()

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [18]:
print(j_)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [21]:
j_.ravel()

array([0, 1, 2, 0, 1, 2, 0, 1, 2])