In [1]:
import numpy as np

Build a dummy Migration Matrix (*MM*)

In [60]:
MM = np.array(
    [
        [0.9371, 0.0602, 0.0026, 0., 0.], 
        [0.193,  0.7296, 0.07,   0.0031, 0],
        [0.0476, 0.2321, 0.6651, 0.0514, 0.0038],
        [0.02,   0.0952, 0.3225, 0.4875, 0.075],
        [0.0057, 0.0252, 0.0901, 0.2,   0.6798]
    ])
print(MM)

[[ 0.9371  0.0602  0.0026  0.      0.    ]
 [ 0.193   0.7296  0.07    0.0031  0.    ]
 [ 0.0476  0.2321  0.6651  0.0514  0.0038]
 [ 0.02    0.0952  0.3225  0.4875  0.075 ]
 [ 0.0057  0.0252  0.0901  0.2     0.6798]]


In [61]:
truth = np.array([1.8, 0.9, 0.4, 0.1, 0.05])*100
print(truth)

[ 180.   90.   40.   10.    5.]


True events undergoing migration matrix leads to expected number of events

In [62]:
mc_exp = np.matmul(MM, truth)
print(mc_exp)

[ 174.2    103.235   56.594   30.318   12.297]


Then I calculate my C-factors or efficiencies

In [63]:
eff = mc_exp/truth
print(eff)

[ 0.96777778  1.14705556  1.41485     3.0318      2.4594    ]


In [76]:
data = [1.8, 0.9, 0.4, 0.1, 0.05]
print(data)

[1.8, 0.9, 0.4, 0.1, 0.05]


In [77]:
truth_pinv = np.matmul(np.linalg.pinv(MM), data)
print(truth_pinv)

[ 1.87415715  0.71642278  0.23026386 -0.17189026  0.05133087]


In [78]:
truth_bin_by_bin = data/eff
print(truth_bin_by_bin)

[ 1.85993111  0.78461762  0.28271548  0.03298371  0.02033016]


In [79]:
print((truth_bin_by_bin-truth_pinv)/truth_pinv)

[-0.00759063  0.09518798  0.2277892  -1.19188816 -0.60393892]
